name: Terraform Destroy
run-name: tf destroy | ${{ github.event_name }} | @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type DESTROY to confirm infrastructure deletion"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: Terraform destroy
    if: ${{ inputs.confirmation == 'DESTROY' }}
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Validate AWS credentials
        run: |
          if ! aws sts get-caller-identity; then
            echo "AWS credentials are not configured correctly."
            exit 1
          fi        

      - name: Initialize Terraform
        run: terraform init -input=false -backend-config="bucket=my-uq-state-bkt" -backend-config="region=ap-south-1"

      - name: Validate Terraform
        run: terraform validate

      - name: Destroy Terraform resources
        run: terraform destroy -auto-approve
